Impelment the module's core features
99xt/cognito-iam-authorizer pull request #1
Opened 2017-07-18 12:58 UTC by deleepa

This PR contains the implementation of the core features for this module.

2017-07-19 04:11 UTC, rehrumesh commented on index.js
> +'use strict';
When it comes to JS, better to use 2 spaces as a tab. Refer Airbnb JS Style guide. We are using that guide inside 99X JS projects.

2017-07-19 04:13 UTC, rehrumesh commented on index.js
> +    console.log(decodedJwt);
If the console log is unnecessary, please remove it. JWT may consists with sensitive data which will ultimately recorded in the CloudWatch logs. May be add a verbose mode for logging throughout the project.

2017-07-19 04:14 UTC, rehrumesh commented on index.js
> +            var policyNames = data["PolicyNames"];
Any particular reason to use var? If not we can replace it with `let`

2017-07-19 04:16 UTC, rehrumesh commented on index.js
> +    let getPolicyNames = function (roleName, callback) {
Consider using named function expression.

2017-07-19 04:17 UTC, rehrumesh commented on index.js
> +                    console.log('get roleName', roleName);
Consider removing `console.log`

2017-07-19 04:17 UTC, rehrumesh commented on index.js
> +                        console.log('get documents', policyDocuments);
Consider removing `console.log`

2017-07-19 04:19 UTC, rehrumesh commented on index.js
> +    var decodedJwt = jwt.decode(jwtToken, {complete: true});
consider using `let` instead of `var`

2017-07-19 04:20 UTC, rehrumesh commented on index.js
> +    if (decodedJwt.payload.iss != iss) {
`!==` instead of `!=`

2017-07-19 04:20 UTC, rehrumesh commented on index.js
> +    if (!(decodedJwt.payload.token_use == 'id' || decodedJwt.payload.token_use == 'access')) {
`===` instead of `==`

2017-07-19 04:20 UTC, rehrumesh commented on index.js
> +    var kid = decodedJwt.header.kid;
Consider `let` over `var`

2017-07-19 04:20 UTC, rehrumesh commented on index.js
> +    var pem = jwkPem[kid];
Consider `let` over `var`

2017-07-19 04:23 UTC, rehrumesh requested changes
Please look into the inline comments

2017-07-19 04:46 UTC, rehrumesh commented on index.js
> +        console.log(statement);
Consider removing console log.

2017-10-26 10:07 UTC, AshanFernando commented
@rehrumesh I will fixed the mentioned points

2017-10-26 10:07 UTC, merged